### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by barbazul** [masaeedu/win-sshfs#2]
**Disclaimer** I am not a windows developer, I have 0 experience with Visual Studio.
I cloned the repository as is. The submodule SSH.NET failed to clone as it is pointing to a non existing commit.

I cloned https://github.com/Foreveryone-cz/SSH.NET-for-winsshfs/ in the SSH.NET folder and then opened Visual Studio 2017 and chose Build ->Build SSHFS.Lib

The build failed with the following output:

```
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: SSHFS.Lib, Configuration: Debug Any CPU ------
1>C:\Users\Barbazul\win-sshfs\Sshfs\SSHFS.Lib\SftpContextStream.cs(50,26,50,38): error CS0122: 'ISftpSession' is inaccessible due to its protection level
1>C:\Users\Barbazul\win-sshfs\Sshfs\SSHFS.Lib\SftpContextStream.cs(58,36,58,48): error CS0122: 'ISftpSession' is inaccessible due to its protection level
1>C:\Users\Barbazul\win-sshfs\Sshfs\SSHFS.Lib\SftpFilesystem.cs(312,44,312,57): error CS0506: 'SftpFilesystem.GetAttributes(string)': cannot override inherited member 'SftpClient.GetAttributes(string)' because it is not marked virtual, abstract, or override
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```

**Comment by masaeedu** [comment]
@barbazul Looks like I need to upload the changes I made to SSH.NET to another fork, then point the submodule at that. I'll do that tomorrow.

**Comment by masaeedu** [comment]
@barbazul Ok, I've rebased to the latest SSH.NET and pushed it to a fork. I can clone a fresh copy, run `git submodule init; git submodule update`, then build with Visual Studio. Let me know if that works for you.

**Comment by barbazul** [comment]
I can confirmed I managed to clone and build successfully after the change!

Thank you
