### ISSUE TITLE
Suggested Usage/Workflow

### ISSUE THREAD

**Issue by ndbeals** [masaeedu/win-sshfs#24]
Hello, thank you for picking up this project and continuing with it.

I used the GUI with the old version, but I'm willing to change to use updated software. That being said, what is your suggested usage/workflow with it.

How do you use it yourself?

- Which shell do you use? (cmd, powershell, msys2?)
- Do you use an ssh agent? (which one?)
- Do you have scripts that mount your drives for you?

Thank you for your answers in advance.

**Comment by masaeedu** [comment]
@ndbeals Hi Nathan. I use this tool in much the same way as I use `sshfs` on Linux, i.e. as a quick way to copy or browse files in remote machines.

Typically I'll be in a Powershell session, and will need to find and copy something from, say, `192.168.5.236`. To do this, I run `sshfs -d X -r / -h 192.168.5.236 -u root -x`, to mount `/` inside the target machine to my `X` drive. I create another Powershell instance, `cd X:` and use the regular tools I have installed (ripgrep, cp etc.) to find and copy what I need. Then I just kill `sshfs`.

The tool is currently incompatible with an SSH agent; you must supply the login password (or the password for your private key, if you're using key based auth) every time you connect. I use the `lpass` CLI tool to manage my passwords, so I can just pipe the password from `lpass` to `sshfs` if I'm logging into some non-disposable machine for which I have the password saved.

If you have some more advanced usage (e.g. you want to remember remote machines), I'd recommend just having your own wrapping scripts/JSON configs which you deserialize and use to call `sshfs`.

**Comment by masaeedu** [comment]
Hopefully, that answers your questions @ndbeals; closing the issue. Feel free to open a new one if you need anything else.

**Comment by ndbeals** [comment]
Oops my apologies, I read your reply when you first sent it, and I was quite satisfied with it. I meant to reply then but I guess I forgot. Thank you very much!
