### ISSUE TITLE
request for support of ECDSA and other types algorithms (now only insecure RSA key is working)

### ISSUE THREAD

**Issue by 4fail** [masaeedu/win-sshfs#26]

**Comment by masaeedu** [comment]
I believe this is something that needs to be added in SSH.NET itself, I don't think there's anything that can be done about this here (unless we're just accidentally calling an API that somehow prevents EC keys from working).

The issue to watch in SSH.NET is probably: https://github.com/sshnet/SSH.NET/issues/20
